# Generated by Django 3.0.3 on 2020-03-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_credencial', '0002_pessoafisica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=32)),
                ('sigla', models.TextField(max_length=6)),
                ('data_inicio', models.DateField()),
                ('descricao', models.TextField(max_length=360)),
                ('realizador', models.ManyToManyField(to='app_credencial.Pessoa')),
            ],
        ),
    ]
