# Generated by Django 3.0.3 on 2020-03-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_credencial', '0004_ingresso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ManyToManyField(to='app_credencial.Evento')),
                ('ingresso', models.ManyToManyField(to='app_credencial.Ingresso')),
                ('pessoa', models.ManyToManyField(to='app_credencial.Pessoa')),
            ],
        ),
    ]
